# Generated by Django 5.2.12 on 2026-09-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_seed_more_test_series_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Optional custom logo image. If uploaded, it is shown instead of the illustrated icon above.', max_length=500, null=True, upload_to='category_logos/'),
        ),
    ]
