# Generated by Django 5.2.12 on 2026-09-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_category_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text="Used for Test Series. Randomize the question order separately for each student's attempt."),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Optional explanation shown to students in "View Solutions" after they submit the test.'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='solution_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list, help_text='Shuffled question ID order for this attempt, when the course has shuffling enabled.'),
        ),
    ]
