# Generated by Django 5.2.12 on 2026-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_question_solution_and_shuffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_logo_image',
            field=models.ImageField(blank=True, help_text='Optional — shown in the admin panel sidebar instead of the logo above. Leave blank to reuse it there.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 200×60px, transparent PNG. Also used for the loading screen and (unless a separate admin panel logo is set below) the admin panel sidebar.', null=True, upload_to='branding/'),
        ),
    ]
