# Generated by Django 5.2.12 on 2026-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_site_settings_admin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='loader_logo_image',
            field=models.ImageField(blank=True, help_text='Optional — shown on the loading screen instead of the logo above. Leave blank to reuse it there.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 200×60px, transparent PNG. Also used for the loading screen and admin panel sidebar, unless separate logos are set for them below.', null=True, upload_to='branding/'),
        ),
    ]
