# Generated by Django 5.2.12 on 2026-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_site_settings_loader_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Optional custom logo image. If uploaded, it is shown instead of the illustrated icon above. Recommended size: 128×128px, square.', max_length=500, null=True, upload_to='category_logos/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_logo_image',
            field=models.ImageField(blank=True, help_text='Optional — shown in the admin panel sidebar instead of the logo above. Leave blank to reuse it there. Recommended size: 100×100px, transparent PNG.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='loader_logo_image',
            field=models.ImageField(blank=True, help_text='Optional — shown on the loading screen instead of the logo above. Leave blank to reuse it there. Recommended size: 200×200px, transparent PNG.', null=True, upload_to='branding/'),
        ),
    ]
