# Generated by Django 5.2.12 on 2026-09-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0085_image_help_text_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
