# Generated by Django 5.2.12 on 2026-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0086_alter_bannerslide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='link',
            field=models.CharField(blank=True, help_text='Optional. Makes the whole slide clickable — opens this link when a student taps anywhere on it (outside the button). e.g. #popular-courses or a full https:// URL', max_length=300),
        ),
    ]
