# Generated by Django 5.2.12 on 2026-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0087_bannerslide_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='panel_access_all',
            field=models.BooleanField(default=True, help_text='Full, unrestricted access to every panel section. Turn off to restrict this admin user to the sections picked below.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='panel_permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of panel section keys this admin user is allowed to access, when access is restricted.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='panel_role',
            field=models.CharField(blank=True, choices=[('subadmin', 'Sub Admin'), ('teacher', 'Teacher')], help_text='Label shown for this admin user; actual access is controlled by the permissions below.', max_length=20),
        ),
    ]
