# Generated by Django 5.2.12 on 2026-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_customuser_panel_access_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional diagram/figure shown with the question, on the panel and to students.', null=True, upload_to='questions/'),
        ),
    ]
