# Generated by Django 5.2.12 on 2026-09-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0089_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtickeritem',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Optional custom logo image. If uploaded, it is shown instead of the vector logo above. Recommended size: 128×128px, square.', max_length=500, null=True, upload_to='exam_ticker_logos/'),
        ),
    ]
