# Generated by Django 5.2.12 on 2026-09-21 17:09

from django.db import migrations


def backfill_notification_tables(apps, schema_editor):
    Notification = apps.get_model('myapp', 'Notification')
    NotificationTable = apps.get_model('myapp', 'NotificationTable')

    for notification in Notification.objects.filter(table_rows__isnull=False).distinct():
        table = NotificationTable.objects.create(notification=notification, title='Important dates', order=0)
        notification.table_rows.update(table=table)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0092_notificationlink_notificationtable_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_notification_tables, noop),
    ]
