# Generated by Django 5.2.12 on 2026-09-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_notification_table_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtablerow',
            name='notification',
        ),
        migrations.AlterField(
            model_name='notificationtablerow',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='myapp.notificationtable'),
            preserve_default=False,
        ),
    ]
