# Generated by Django 5.2.12 on 2026-09-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0094_remove_notificationtablerow_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdatepost',
            name='body',
            field=models.TextField(help_text='Basic HTML (e.g. <p>, <b>, <ul>, <table>) is allowed.'),
        ),
        migrations.CreateModel(
            name='DailyUpdatePostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Key facts', help_text='e.g. Key Facts, Match Scorecard, Mission Details', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='myapp.dailyupdatepost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dailyupdateposttablerow',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='myapp.dailyupdateposttable'),
        ),
    ]
