# Generated by Django 5.2.12 on 2026-09-22 06:33

from django.db import migrations


def backfill_daily_post_tables(apps, schema_editor):
    DailyUpdatePost = apps.get_model('myapp', 'DailyUpdatePost')
    DailyUpdatePostTable = apps.get_model('myapp', 'DailyUpdatePostTable')

    for post in DailyUpdatePost.objects.filter(table_rows__isnull=False).distinct():
        table = DailyUpdatePostTable.objects.create(post=post, title='Key facts', order=0)
        post.table_rows.update(table=table)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_alter_dailyupdatepost_body_dailyupdateposttable_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_daily_post_tables, noop),
    ]
