# Generated by Django 5.2.12 on 2026-09-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0096_daily_post_table_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyupdateposttablerow',
            name='post',
        ),
        migrations.AlterField(
            model_name='dailyupdateposttablerow',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='myapp.dailyupdateposttable'),
            preserve_default=False,
        ),
    ]
