# Generated by Django 5.2.12 on 2026-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0097_remove_dailyupdateposttablerow_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='prize_label',
        ),
        migrations.RemoveField(
            model_name='quizzoneattempt',
            name='final_prize_label',
        ),
        migrations.AddField(
            model_name='quizgamesettings',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=30, help_text='How long a student has to answer each question.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-language text, e.g. {"hi": {"text": "...", "option_a": "..."}}. Missing languages fall back to the English fields above.'),
        ),
        migrations.AddField(
            model_name='quizzoneattempt',
            name='final_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
