# Generated by Django 5.2.12 on 2026-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0098_remove_quizquestion_prize_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_more_details',
            field=models.TextField(blank=True, help_text='Optional extra info shown on the Contact Us page below the contact details — e.g. an alternate branch, a WhatsApp-only number, or special instructions.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_timings',
            field=models.CharField(blank=True, default='Mon–Sat, 8 am – 8 pm', help_text='Shown as "Working hours" on the Contact Us page and in the footer.', max_length=150),
        ),
    ]
