# Generated by Django 5.2.12 on 2026-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0099_sitesettings_contact_more_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro',
            field=models.TextField(blank=True, default="We're here to help with anything related to your courses, orders or account. Reach out to us using any of the details below, and our team will get back to you as soon as possible.", help_text='Shown as the intro paragraph on the Contact Us page, above the contact form.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_map_url',
            field=models.URLField(blank=True, help_text='Optional — paste the embeddable map link from Google Maps (Share → Embed a map → copy the src URL) to pin the exact location. Falls back to a search using the address above if left blank.'),
        ),
        migrations.AlterField(
            model_name='extrapage',
            name='page',
            field=models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_conditions', 'Terms & Conditions'), ('refund_cancellation', 'Refund & Cancellation Policy'), ('shipping_delivery', 'Shipping & Delivery Policy'), ('disclaimer', 'Disclaimer')], max_length=25, unique=True),
        ),
    ]
