# Generated by Django 5.2.12 on 2026-09-22 07:04

from django.db import migrations


def seed_contact_intro(apps, schema_editor):
    ExtraPage = apps.get_model('myapp', 'ExtraPage')
    SiteSettings = apps.get_model('myapp', 'SiteSettings')

    old_page = ExtraPage.objects.filter(page='contact_us').first()
    if not old_page or not old_page.content.strip():
        return

    first_paragraph = old_page.content.strip().split('\n\n')[0].strip()
    if not first_paragraph:
        return

    settings_obj, _ = SiteSettings.objects.get_or_create(pk=1)
    settings_obj.contact_intro = first_paragraph
    settings_obj.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0100_sitesettings_contact_intro_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_contact_intro, noop),
    ]
