# Generated by Django 5.2.12 on 2026-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0101_seed_contact_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsection',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional time limit for this section, in minutes. Counted from the moment the student opens the section — once it runs out, the section locks and the test moves on to the next one. Leave blank for no per-section limit.', null=True),
        ),
    ]
