# Generated by Django 5.2.12 on 2026-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0102_testsection_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='all_questions_mandatory',
            field=models.BooleanField(default=False, help_text='Used for Test Series. Prevent the user from skipping questions. Student will not be able to skip questions.'),
        ),
        migrations.AddField(
            model_name='course',
            name='disable_partial_marking',
            field=models.BooleanField(default=False, help_text='Used for Test Series. Disable partial marking for the test. Marks will be rewarded only if the entire answer is correct, with no marks for partially correct answers.'),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_optional_questions_in_section',
            field=models.BooleanField(default=False, help_text='Used for Test Series. Enable optional questions in section feature for the test. You will be able to add sections with optional questions in them, and the student can choose among the optional question(s) they want to attempt in that particular section.'),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_optional_section',
            field=models.BooleanField(default=False, help_text='Used for Test Series. Enable optional sectional feature for the test. You will be able to mark some of the sections as optional, and student can choose among the optional section(s) they want to attempt. Sections not marked "optional" will be compulsory to attempt.'),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_sectional_timing',
            field=models.BooleanField(default=False, help_text='Used for Test Series. Enable fixed timing for each of the test sections. Student will not be able to change section before the allotted duration is over for that section.'),
        ),
        migrations.AddField(
            model_name='course',
            name='languages_supported',
            field=models.JSONField(blank=True, default=list, help_text='Used for Test Series. Questions have to be uploaded in the languages you select here. Leave empty to allow every supported language.'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Used when the section has "Maximum optional questions" set. Student can choose to attempt this among the optional questions in this section.'),
        ),
        migrations.AddField(
            model_name='testsection',
            name='max_optional_questions',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Used when "Enable Optional Questions in Section" is on for the test. Maximum optional questions in this section that count towards the score. Use 0 to disable optional questions for this section.'),
        ),
    ]
