# Generated by Django 5.2.12 on 2026-09-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0103_course_all_questions_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Marks deducted for a wrong answer to this question. Leave blank to use the section's default negative marks.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testsection',
            name='disable_shuffling',
            field=models.BooleanField(default=False, help_text='Optional. Keep this section\'s questions in a fixed order even when the test has "Shuffle questions" enabled.'),
        ),
        migrations.AddField(
            model_name='testsection',
            name='negative_marks_options',
            field=models.JSONField(blank=True, default=list, help_text='Standard negative-mark values for this section, e.g. [0.25, 0.5, 1]. Shown as quick picks in the Question Edit/Insert interface.'),
        ),
        migrations.AddField(
            model_name='testsection',
            name='positive_marks_options',
            field=models.JSONField(blank=True, default=list, help_text='Standard positive-mark values for this section, e.g. [1, 2, 4]. Shown as quick picks in the Question Edit/Insert interface.'),
        ),
        migrations.AddField(
            model_name='testsection',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-language section name, e.g. {"hi": {"name": "..."}, "kn": {"name": "..."}}. Missing languages fall back to the English name above.'),
        ),
        migrations.AlterField(
            model_name='testsection',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default marks deducted for a wrong answer in this section — used when a question does not set its own negative marks.', max_digits=5),
        ),
    ]
