# Generated by Django 5.2.12 on 2026-09-26 14:40

from django.db import migrations, models


def set_initial_status(apps, schema_editor):
    Course = apps.get_model('myapp', 'Course')
    Course.objects.filter(is_active=False).exclude(status='archived').update(status='archived')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0104_question_negative_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'In Review'), ('drafting', 'Question Drafting'), ('archived', 'Archived')], default='published', help_text='Workflow state. Only "Published" tests are shown publicly — the others stay hidden while the item is a draft, under review, or archived.', max_length=20),
        ),
        migrations.RunPython(set_initial_status, noop),
    ]
