# Generated by Django 5.2.12 on 2026-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0105_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional. Shown instead of the desktop banner on phone-width screens. Recommended size: 800×900px (taller/narrower crop). Leave blank to reuse the desktop banner.', null=True, upload_to='banner/mobile/'),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='mobile_image_url',
            field=models.URLField(blank=True, help_text='Used only if no mobile image is uploaded above'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Desktop banner. Recommended size: 1600×600px.', null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='Used only if no desktop image is uploaded above'),
        ),
    ]
